.travis.yml:
  env:
    global:
      - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
      - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
      - GLIDE_HOME="${HOME}/.glide"
    matrix:
      - TEST_TYPE=small
  deploy:
    access_key_id: AKIAINMB43VSSPFZISAA
    secret_access_key:
      secure: NO/T51J8AC8jNfFN7xSEx/oOEp+Ntvk/7WICKwhRA6fkDf9PeCaBOT3lGzgvHZCyy9PYGbfxe42X12yUuNoAYGs631vt0Pfi834pnwQtFd7WlnCanl3yADBaIVEKpfxQbINb1NYxWviqK0Xu7c/vGIkeZW36aUV3EF+Zkuskp7/BnvDsic1pumqTNiwSWfqT++DlcWo05kx6YH8wsF4+el+6YERdUZQ7Mu0j2D3jlZjEHeolLKHk7fPOP1Atr1slasqqAGSE10sFTUQrM/a0R1FiTDvxRt8DKP3d/CMSD4sbIPHAC6wjtzNvQiA1JRAQVqDU4suwYiyPJMQpIRXDRHasxTdQxGH+1Dm5dBIJQQSgHAKVoFbIkBcNhVa3DGWhQyWoxuqgwGf81IsTyN5+0dC99sJIUCAD998mYMi8CTmxCcek7A47YgFrlyAAlxn3OrsIf/ED7jDWoWH5iIkUj0Iy7PCcnbopOQZjoX2DzZYBYkzsKzxK0xcV23IJRDLcdhfNTDTMcMhTeVWsBZe1f0zl7vx3BrJE3WqNvRmJ0LgBQCSO5HbnvBwTGZvo48/KtIggDMn0DRnewbfNL7jfRhiy4pPh6TC2M7Y74YCUj7A4fZFWf+Yuq6Vi4oH/4IF1MjYXeQCVgxLDaXlXv+e+Z1UqwRcJL6Uooydh1mdKIDw=
    api_key:
      secure: BxPzO6z768C2Sc6lijoRJNhMiL+HnUfcLWXB99WVQM++OaY+3t98EjabETvPfgCfl3gxyBrTnfn3umuj3dbFCSspptY+mnI/sjvvu3yfHMOPOGT+5yhPzBir+WA5GN4gAlAwvOoMYTUJf//An7b4Pa+98Tz52MJMtYvNPTtHmG8K4G6xhWRtkuIRp7jMrBJpp27RHBW03csBcX+wYwaPjTtRev4/VhnbQxquSq6EYWSXlxBPNt24y2zQJ5qcFs50XEz6FVzXp9S4rN9ngVbCHfdmwM/JxJCoeKgjDJErVb8VISNUHUHTin+4vtAU4ypheyWzxNcpGeCIECd7eNSwXFoCAZlmJIORDiWX3BlE7Hjxn+J3h0hw2EkOt6B/ReaY0fdg88xWZCGgUYiXTt4EQ7h0XugpQjTme/3w0efWufikwvgJi7EG1ITKTmTwvh8ps8IkU9WigIqcTacTLE051EIVhVsiUZJsuGgIdhQ3d3XCGS500GxNifrTxovOu2l0D3DKXoMbzt9quDHWSU28iJZsnAaYAKGt1M4rvahuC0KQ2d64Qcy4qIzoFc2O2FY9xqZGYAn0h0uPdzCgBj9FoHu3D/YEUDM7XTTws0hVT94/HpDcCiqd4zuE95cD0fHCjQfCWOBf9qMxbKWTAyHslMGtTwlIFL1IaAjLNpyI3SI=
